trigger:
- master

pr: none

resources:
  repositories:
  - repository: helmRepo
    type: github
    endpoint: vigneshraj90
    name: vigneshraj90/helm-library

pool:
  vmImage: 'ubuntu-latest'

variables:
  repo: helm-library
  helmRepo: helm-library
  helmRepositoryUrl: git@github.com:vigneshraj90/helm-library.git
  version:
  releaseExists: false

steps: 
- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'kubeconn'
    command: 'install'
    chartType: 'FilePath'
    chartPath: 'https://github.com/Azure-Samples/helm-charts/tree/master/chart-source/azure-vote-osba'
    overrideValues: '--set title="Winter Sports" --set value1=Ski --set value2=Snowboard'
