trigger:
- master

pr: none

resources:
  repositories:
  - repository: helmRepo
    type: github
    endpoint: vigneshraj90
    name: vigneshraj90/helm-library

pool:
  vmImage: 'ubuntu-latest'

variables:
  repo: helm-library
  helmRepo: helm-library
  helmRepositoryUrl: git@github.com:vigneshraj90/helm-library.git
  version:
  releaseExists: false

steps: 
  - checkout: self
    displayName: Clone repository

  - task: HelmInstaller@1
    displayName: Install Helm
    inputs:
      helmVersionToInstall: 'latest'

  - checkout: helmRepo
    displayName: Clone Helm repository

  - script: |
      helm package $(Agent.BuildDirectory)/s/$(repo)/$(repo) --destination $(Agent.BuildDirectory)/s/$(helmRepo)
    displayName: Package Helm
